version: "3.9"

services:
  web:
    build: .
    #command: >
     # sh -c "
     # ls
     # && npm install
     # && npm run prod
     # "
    volumes:
      - .:/code
    ports:
      - "8081:3000"
    env_file:
      - .env.development
