version: "3.9"

services:
  web:
    build: .
    #command: >
     # sh -c "
     # ls
     # && npm install
     # && npm run prod
     # "
    volumes:
      - .:/code
    ports:
      - "8080:3000"
    env_file:
      - .env.development
    #network_mode: host
    extra_hosts:
      - "app.emailstats.com:192.168.65.2"
      - "back.emailstats.com:192.168.65.2"
